### ISSUE TITLE
bert_embedding example throws error

### ISSUE THREAD

**Issue by BenWiseman** [tofunlp/sister#161]
```
>>> bert_embedding = sister.BertEmbedding(lang="en")
>>> sentence = "I am a dog."
>>> vector = bert_embedding(sentence)
AttributeError: 'NoneType' object has no attribute 'batch_encode_plus'
```

I'm not sure what the issue is, it downloaded BERT, installed sentencepiece and all, but is unhappy. MeanEmbedding() works perfectly, so I'm guessing something is off in BERT? 

`
OS: Pop!_OS 20.10 x86_64 
Kernel: 5.11.0-7612-generic 
Shell: bash 5.0.17 
Resolution: 5120x1440 
DE: GNOME 
CPU: AMD Ryzen 9 3900X (24) @ 3.800GHz 
 GPU: NVIDIA GeForce RTX 2080 Rev. A 
Memory: 7855MiB / 32096MiB 
                                                                                         
`

**Comment by sobamchan** [comment]
Thanks for reporting!

It seems like in the installation process, it fails to install the proper version of one dependency (transformers).
I will look into this and get back to you in few days.

**Comment by BenWiseman** [comment]
Thanks!

**Comment by sobamchan** [comment]
@BenWiseman 

Hi, I failed to replicate this issue on my local machine, it just worked fine.

Could you check the version of [huggingface/transformers](https://github.com/huggingface/transformers) package by running `pip freeze | grep transformers`?
