### ISSUE TITLE
Could you please add the french fasttext bin model to this package, I am new to programming and don't know how to do it myself. Thanks in advance!

### ISSUE THREAD

**Issue by MistryWoman** [tofunlp/sister#66]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sobamchan** [comment]
Thanks for the suggestion!
I will add french in a few days.

**Comment by sobamchan** [comment]
Hi, @MistryWoman 
Now French is added.

You can use it by,

```py
import sister

sentence_embedding = sister.MeanEmbedding(lang="fr")

sentence = "Bonjour le monde ."
vector = sentence_embedding(sentence)
```

**Comment by MistryWoman** [comment]
Thank you @sobamchan  , really appreciate it ! I'll cite your package in the references for my project.
